name: Push to ADX

on:
    push:
        branches:
            - "feature/initial-deploy"

jobs:
    build-patch:
        runs-on: ubuntu-latest
        environment: dev

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install DeltaKusto
              run: |
                  clientVersion=$(curl https://delta-kusto.azurefd.net/clientVersion/unique?fromClientVersion=0)
                  # Display the version on console
                  echo "Client Version:  $clientVersion"
                  wget https://github.com/microsoft/delta-kusto/releases/download/$clientVersion/delta-kusto-linux.tar.gz
                  tar --extract --file delta-kusto-linux.tar.gz
                  chmod +x ./delta-kusto

            - name: Prepare deployment for environment
              uses: mikefarah/yq@master
              with:
                  cmd: yq -i '(.. | select(tag == "!!str")) |= envsubst(nu)' "deployment.yaml"
